### ISSUE TITLE
Remote fetching example

### ISSUE THREAD

**Issue by abelrgr** [indrimuska/angular-selector#36] opened 2016-04-01 18:34 UTC
When attemp the "Remote fetching" example I cannot select the item when the list is retrieved:

![anim](https://cloud.githubusercontent.com/assets/1250071/14216401/879bc09e-f816-11e5-83cc-ce7bd005bfb3.gif)

My Chrome version are: Version 49.0.2623.110 (64-bit)

**Comment by indrimuska** [comment] 2016-04-03 23:45
Thank you @chule143 for reporting this, maybe this is caused by last fix on issue #34. I'm looking for a solution.

**Comment by Nishchit14** [comment] 2016-04-04 09:58
I face same bug on 1.3.2

1.1.4 works fine

**Comment by indrimuska** [comment] 2016-04-04 15:26
I've just released [version 1.3.5](https://github.com/indrimuska/angular-selector/releases/tag/1.3.5).
It should resolve this issue, please let me know if it still persists. :)

**Comment by indrimuska** [comment] 2016-04-14 08:37
I'm going to close this issue, feel free to open again if the problem still persists.

**Closed as completed by indrimuska** 2016-04-14 08:37 UTC
Labels: bug
