### ISSUE TITLE
How to do multi select of group?

### ISSUE THREAD

**Issue by donotdont** [indrimuska/angular-selector#12] opened 2016-01-16 06:28 UTC
How to do multi select of group that use one option? link this
![screenshot from 2016-01-16 13 18 42](https://cloud.githubusercontent.com/assets/1459713/12370882/7ff41efc-bc54-11e5-9e00-d58122314c9b.png)
HTML
![screenshot from 2016-01-16 13 21 22](https://cloud.githubusercontent.com/assets/1459713/12370912/f4926dfe-bc54-11e5-8a12-a91d86beb576.png)
JS
![screenshot from 2016-01-16 13 20 35](https://cloud.githubusercontent.com/assets/1459713/12370913/0047e9c6-bc55-11e5-86ad-cc06db7bc7b3.png)

Code : http://embed.plnkr.co/pyADrWc9tWq6X9K94Sa1/

**Comment by donotdont** [comment] 2016-01-16 07:11
http://embed.plnkr.co/pyADrWc9tWq6X9K94Sa1/

**Comment by indrimuska** [comment] 2016-01-17 14:06
Hi @donotdont,
I really can't understand where your problem is, I need more information to figure it out.
Do you need help to select more than one value together?
Could you please tell me the steps to get into your scenario?

**Comment by donotdont** [comment] 2016-01-18 02:35
Hi @indrimuska ,
i mean select on once source option, ex. when i selected option on group number 1 => Current value as [0,1,2,3,4,5] in this picture, and i move to click select on group number 2. it's will not show option of selected on group number 1, Group number 2 show => Current value as [6,7,8,9,10, ... ].

**Comment by indrimuska** [comment] 2016-01-18 10:36
I don't know if I've followed the correct steps, that's what I've done:
1. I've selected all values from the FIRST select (label says "Group 1", but it's not the only one with this name)
2. I've clicked on the button below "Add"
3. I've changed my focus on the next select (label says "Group 2", and it's the only one!)
4. Now I see NO options

So I analyzed your code and I've created this [updated plunker](http://plnkr.co/edit/a2LcaTktiKcYfpeC7ASC?p=preview).
As I can see, you have two repeating groups of select, so I added a little number to each one before label name, respectively `(1)` at line 27 and `(2)` at line 54.

![screenshot](https://cloud.githubusercontent.com/assets/1561134/12388935/13c3077e-bdd6-11e5-854b-6ae0f3b74b7e.png)

After performing the same previous steps, I see that **Group 2** now has label **(1) Group 2**, so the problem is in the method that returns the options list: **`comanationOption(item.comanation)`**.
I don't know why this method returns an array of `null` values, as you can see by printing:
`{{ comanationOption(item.comanation) | json }}` - see this [plunker](http://plnkr.co/edit/rsG6ehX7UzYDBWtJGUBc?p=preview)

As you can see, this is not an issue of _Angular Selector_, so I'm going to close this.

**Closed as completed by indrimuska** 2016-01-18 10:36 UTC
Labels: help wanted

**Comment by donotdont** [comment] 2016-01-18 11:07
Thank you very much.
