### ISSUE TITLE
Selected elements are removed after fetching remote data in a multiple selector

### ISSUE THREAD

**Issue by ssotomayor** [indrimuska/angular-selector#66] opened 2016-11-04 16:09 UTC
Selected options are removed after fetching in a multi selector.

Plunker (same as #57): http://plnkr.co/edit/CGY47bqX0dLnFkrVY3aB?p=preview

### Steps to reproduce the issue:

Click the selector
Select 3 options, say, Afghanistan - Aland Islands - Albania
Type "Bra" to get "Brazil"
Select "Brazil".

Notice  "Afghanistan - Aland Islands - Albania" are removed after selecting "Brazil".

**Comment by indrimuska** [comment] 2016-11-04 18:35
Duplicate of #57.

**Closed as completed by indrimuska** 2016-11-04 18:35 UTC
Labels: duplicate
